import { useState } from "react";
import { Button } from "../../../components/ui/button";
import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
} from "../../../components/ui/card";
import { Badge } from "../../../components/ui/badge";
import { Separator } from "../../../components/ui/separator";
import { Alert, AlertDescription } from "../../../components/ui/alert";
import {
  Check,
  Clock,
  MapPin,
  Truck,
  Shield,
  Copy,
  PackageCheck,
  CircleDot,
  Circle,
} from "lucide-react";

interface TransactionRoomShippingProps {}

const trackingTimeline = [
  {
    id: 1,
    label: "Payment Confirmed",
    status: "completed" as const,
    time: "Nov 28, 11:45 AM",
    description: "Escrow payment secured",
  },
  {
    id: 2,
    label: "Label Created",
    status: "active" as const,
    time: "Nov 28, 11:47 AM",
    description: "Shipping label generated by seller",
  },
  {
    id: 3,
    label: "Picked up by Carrier",
    status: "pending" as const,
    time: "Pending",
    description: "Awaiting FedEx pickup",
  },
  {
    id: 4,
    label: "Out for Delivery",
    status: "pending" as const,
    time: "Pending",
    description: "Package en route to destination",
  },
];

export function TransactionRoomShipping({}: TransactionRoomShippingProps) {
  const [copiedTracking, setCopiedTracking] = useState(false);

  const handleCopyTrackingNumber = () => {
    navigator.clipboard.writeText("TRK-9988-7766");
    setCopiedTracking(true);
    setTimeout(() => setCopiedTracking(false), 2000);
  };

  return (
    <div className="lg:col-span-2 space-y-6">
      {/* Escrow Alert */}
      <Alert className="border-green-500/30 bg-green-500/5">
        <Shield className="h-4 w-4 text-green-500" />
        <AlertDescription className="text-sm text-green-500/90">
          <strong>Escrow Secured:</strong> Your payment of $1,400 is protected.
          Funds will be released to the seller after you confirm delivery.
        </AlertDescription>
      </Alert>

      {/* Status Card */}
      <Card className="border-border">
        <CardContent className="p-6">
          <div className="flex items-center gap-6">
            {/* Large Package Icon */}
            <div className="flex-shrink-0">
              <div className="w-20 h-20 rounded-full bg-accent/10 border-2 border-accent/30 flex items-center justify-center">
                <PackageCheck className="h-10 w-10 text-accent" />
              </div>
            </div>

            {/* Status Info */}
            <div className="flex-1">
              <h2 className="text-2xl mb-2">Shipment In Progress</h2>
              <p className="text-sm text-muted-foreground mb-3">
                The seller has created a shipping label. Your package is
                awaiting carrier pickup.
              </p>
              <div className="flex items-center gap-2">
                <Badge className="bg-green-500/20 text-green-500 border-green-500/50">
                  <Shield className="h-3 w-3 mr-1" />
                  Escrow Secured
                </Badge>
                <Badge className="bg-accent/20 text-accent border-accent/50">
                  <Clock className="h-3 w-3 mr-1" />
                  Est. Delivery: 2-3 Days
                </Badge>
              </div>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Tracking Information Card */}
      <Card className="border-border">
        <CardHeader>
          <div className="flex items-center justify-between">
            <CardTitle className="text-lg flex items-center gap-2">
              <Truck className="h-5 w-5 text-accent" />
              Tracking Information
            </CardTitle>
          </div>
        </CardHeader>
        <CardContent className="space-y-6">
          {/* Carrier Info */}
          <div className="flex items-center justify-between p-4 rounded-lg bg-secondary/50 border border-border">
            <div className="flex items-center gap-4">
              {/* Carrier Logo Placeholder */}
              <div className="w-16 h-16 rounded bg-gradient-to-br from-purple-600 to-blue-600 flex items-center justify-center">
                <Truck className="h-8 w-8 text-white" />
              </div>
              <div>
                <div className="text-xs text-muted-foreground mb-1">
                  Carrier
                </div>
                <div className="text-lg">FedEx Express</div>
                <div className="text-xs text-muted-foreground">
                  2-3 Business Days
                </div>
              </div>
            </div>
          </div>

          {/* Tracking Number */}
          <div>
            <div className="text-xs text-muted-foreground mb-2">
              Tracking Number
            </div>
            <div className="flex items-center gap-2 p-4 rounded-lg bg-secondary border border-border">
              <code className="flex-1 font-mono text-lg tracking-wider text-accent">
                TRK-9988-7766
              </code>
              <Button
                variant="ghost"
                size="sm"
                onClick={handleCopyTrackingNumber}
              >
                {copiedTracking ? (
                  <Check className="h-4 w-4 text-green-500" />
                ) : (
                  <Copy className="h-4 w-4" />
                )}
              </Button>
            </div>
          </div>

          <Separator />

          {/* Status Timeline */}
          <div>
            <h3 className="text-sm mb-4">Shipment Status</h3>
            <div className="space-y-4">
              {trackingTimeline.map((item, index) => {
                const isActive = item.status === "active";
                const isCompleted = item.status === "completed";
                // const isPending = item.status === "pending";

                return (
                  <div key={item.id} className="flex gap-4">
                    {/* Timeline Indicator */}
                    <div className="flex flex-col items-center">
                      <div
                        className={`w-8 h-8 rounded-full flex items-center justify-center border-2 ${
                          isCompleted
                            ? "bg-green-500 border-green-500"
                            : isActive
                            ? "bg-accent border-accent"
                            : "bg-secondary border-border"
                        }`}
                      >
                        {isCompleted ? (
                          <Check className="h-4 w-4 text-background" />
                        ) : isActive ? (
                          <CircleDot className="h-4 w-4 text-background" />
                        ) : (
                          <Circle className="h-4 w-4 text-muted-foreground" />
                        )}
                      </div>
                      {index < trackingTimeline.length - 1 && (
                        <div
                          className={`w-0.5 h-12 mt-1 ${
                            isCompleted ? "bg-green-500" : "bg-border"
                          }`}
                        />
                      )}
                    </div>

                    {/* Timeline Content */}
                    <div className="flex-1 pb-4">
                      <div
                        className={`text-sm mb-1 ${
                          isActive
                            ? "text-accent"
                            : isCompleted
                            ? "text-green-500"
                            : "text-muted-foreground"
                        }`}
                      >
                        {item.label}
                        {isActive && (
                          <Badge className="ml-2 bg-accent/20 text-accent border-accent/50 text-xs">
                            Current
                          </Badge>
                        )}
                      </div>
                      <div className="text-xs text-muted-foreground mb-1">
                        {item.time}
                      </div>
                      <div className="text-xs text-muted-foreground">
                        {item.description}
                      </div>
                    </div>
                  </div>
                );
              })}
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Shipping Details */}
      <Card className="border-border">
        <CardHeader>
          <CardTitle className="text-lg flex items-center gap-2">
            <MapPin className="h-5 w-5 text-accent" />
            Shipping Details
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="grid md:grid-cols-2 gap-4">
            {/* From */}
            <div className="p-4 rounded-lg bg-secondary/50 border border-border">
              <div className="text-xs text-muted-foreground mb-2">
                From (Seller)
              </div>
              <div className="text-sm">
                <div>John Smith</div>
                <div className="text-muted-foreground mt-1">
                  San Francisco, CA
                </div>
                <div className="text-xs text-muted-foreground mt-1">
                  (Address masked for privacy)
                </div>
              </div>
            </div>

            {/* To */}
            <div className="p-4 rounded-lg bg-secondary/50 border border-border">
              <div className="text-xs text-muted-foreground mb-2">To (You)</div>
              <div className="text-sm">
                <div>John Doe</div>
                <div className="text-muted-foreground mt-1">
                  123 Main Street, Apt 4B
                </div>
                <div className="text-muted-foreground">New York, NY 10001</div>
                <div className="text-muted-foreground mt-1">(555) 123-4567</div>
              </div>
            </div>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
